update

diff --git a/maincourse/fractol/Makefile b/maincourse/fractol/Makefile
--- a/maincourse/fractol/Makefile
+++ b/maincourse/fractol/Makefile
@@ -1,82 +1,80 @@
 # Configuration
-NAME	= fractol
-LIBFT	= libft.a
-LDIR	= libft/
-CC		= cc
-CFLAGS	= -Wall -Wextra -Werror -g -fsanitize=address -Ofast
-LIBS	= -ldl -pthread -lm
-RM		= rm -rf
-MK		= mkdir -p
-SDIR	= src
-ODIR	= obj
+NAME = fractol
+CC = cc
+CFLAGS = -Wall -Wextra -Werror -g
+LIBS = -ldl -pthread -lm
+RM = rm -rf
+MK = mkdir -p
+BIN = bin
+SDIR = src
+ODIR = obj
 
 # Include directories
 INCDIR = include
 HEADERS = -I $(INCDIR) -I $(MLXDIR)/include
 
 # Dependencies
-# DEPS = $(wildcard $(INCDIR)/*.h)
+DEPS = $(wildcard $(INCDIR)/*.h)
 
-# # Source and Object Files
-# SRCS = $(wildcard $(SDIR)/*.c) $(wildcard $(SDIR)/*/*.c)
-SRCS := $(shell find ./src -iname "*.c")
+# Source and Object Files
+SRCS = $(wildcard $(SDIR)/*.c) $(wildcard $(SDIR)/*/*.c)
 OBJS = $(SRCS:$(SDIR)/%.c=$(ODIR)/%.o)
-
-# # Source and Object Files
-# SRCS    = $(addprefix $(SDIR), main.c, mandelbrot.c, colors.c)
-# OBJS    = $(patsubst $(SDIR)%.c,$(ODIR)%.o,$(SRCS))
+DEPFILES = $(OBJS:.o=.d) # Add this line to create dependency file paths
 
 # MLX42
 MLXDIR = MLX42
 LIBMLX = $(MLXDIR)/build/libmlx42.a
 MLX_REPO = https://github.com/codam-coding-college/MLX42.git
 LIBS += -lglfw -L"/Users/$(USER)/.brew/opt/glfw/lib/" $(LIBMLX)
-HEADERS = -I $(INCDIR) -I $(MLXDIR)/include
+HEADERS += -I $(INCDIR) -I $(MLXDIR)/include
 
-all: dependencies libft $(LIBMLX) $(NAME)
+all: dependdown $(LIBMLX) $(NAME)
+
+# Dependency handling rules
+-include $(DEPFILES) # Include the dependency files in the Makefile
 
 # Dependency installation (brew, cmake, glfw)
-# dependencies:
-# 	@if [ -x "$$HOME/homebrew/bin/brew" ] || [ -x "$$HOME/.brew/bin/brew" ]; then \
-# 		echo "brew is already installed"; \
-# 	else \
-# 		echo "Brew not found"; \
-# 		read -p "Do you want to install brew? y/n: "  brewchoice; \
-# 		if [ "$$brewchoice" = "y" ]; then \
-# 			rm -rf $$HOME/.brew && git clone --depth=1 https://github.com/Homebrew/brew $$HOME/.brew && \
-# 			echo 'export PATH=$$HOME/.brew/bin:$$PATH' >> $$HOME/.zshrc && source $$HOME/.zshrc && brew update; \
-# 			echo "Brew successfully installed"; \
-# 		else \
-# 			echo "Exit"; \
-# 			exit 2; \
-# 		fi \
-# 	fi
-# 	@if [ -d "$$HOME/homebrew/opt/cmake/bin" ] || [ -d "$$HOME/.brew/opt/cmake/bin" ]; then \
-# 		echo "cmake is already installed"; \
-# 	else \
-# 		echo "cmake not found"; \
-# 		read -p "Do you want to install cmake? y/n: " cmakechoice; \
-# 		if [ "$$cmakechoice" = "y" ]; then \
-# 			brew install cmake; \
-# 			echo "cmake successfully installed"; \
-# 		else \
-# 			echo "Exit"; \
-# 			exit 2; \
-# 		fi \
-# 	fi
-# 	@if [ -d "$$HOME/homebrew/opt/glfw/lib" ] || [ -d "$$HOME/.brew/opt/glfw/lib" ]; then \
-# 		echo "glfw is already installed"; \
-# 	else \
-# 		echo "glfw not found"; \
-# 		read -p "Do you want to install glfw? y/n: " glfwchoice; \
-# 		if [ "$$glfwchoice" = "y" ]; then \
-# 			brew install glfw; \
-# 			echo "glfw successfully installed"; \
-# 		else \
-# 			echo "Exit"; \
-# 			exit 2; \
-# 		fi \
-# 	fi
+dependdown:
+	@if [ -x "$$HOME/homebrew/bin/brew" ] || [ -x "$$HOME/.brew/bin/brew" ]; then \
+		echo "brew is already installed"; \
+	else \
+		echo "Brew not found"; \
+		read -p "Do you want to install brew? y/n: "  brewchoice; \
+		if [ "$$brewchoice" = "y" ]; then \
+			rm -rf $$HOME/.brew && git clone --depth=1 https://github.com/Homebrew/brew $$HOME/.brew && \
+			echo 'export PATH=$$HOME/.brew/bin:$$PATH' >> $$HOME/.zshrc && source $$HOME/.zshrc && brew update; \
+			echo "Brew successfully installed"; \
+		else \
+			echo "Exit"; \
+			exit 2; \
+		fi \
+	fi
+	@if [ -d "$$HOME/homebrew/opt/cmake/bin" ] || [ -d "$$HOME/.brew/opt/cmake/bin" ]; then \
+		echo "cmake is already installed"; \
+	else \
+		echo "cmake not found"; \
+		read -p "Do you want to install cmake? y/n: " cmakechoice; \
+		if [ "$$cmakechoice" = "y" ]; then \
+			brew install cmake; \
+			echo "cmake successfully installed"; \
+		else \
+			echo "Exit"; \
+			exit 2; \
+		fi \
+	fi
+	@if [ -d "$$HOME/homebrew/opt/glfw/lib" ] || [ -d "$$HOME/.brew/opt/glfw/lib" ]; then \
+		echo "glfw is already installed"; \
+	else \
+		echo "glfw not found"; \
+		read -p "Do you want to install glfw? y/n: " glfwchoice; \
+		if [ "$$glfwchoice" = "y" ]; then \
+			brew install glfw; \
+			echo "glfw successfully installed"; \
+		else \
+			echo "Exit"; \
+			exit 2; \
+		fi \
+	fi
 
 $(LIBMLX): $(MLXDIR)
 	@cmake $(MLXDIR) -B $(MLXDIR)/build && make -C $(MLXDIR)/build -j4
@@ -88,17 +86,14 @@ $(MLXDIR):
 	fi
 
 $(NAME): $(OBJS)
-	@$(CC) $(CFLAGS) $(OBJS) $(LIBS) $(HEADERS) -o $(NAME) $(LDIR)$(LIBFT)
+	@$(CC) $(CFLAGS) $(OBJS) $(LIBS) $(HEADERS) -o $(NAME)
 	@echo "Compilation complete: $(NAME)"
 
 $(ODIR)/%.o: $(SDIR)/%.c $(DEPS)
 	@$(MK) $(dir $@)
-	@$(CC) $(CFLAGS) -c $< -o $@ $(HEADERS)
+	@$(CC) $(CFLAGS) -MMD -MP -c $< -o $@ $(HEADERS) # Add -MMD and -MP flags here
 
-# Compiling libft
-libft:
-	@echo "compiling libft"
-	@$(MAKE) -C $(LDIR)
+.PHONY: all clean fclean re
 
 clean:
 	@$(RM) $(ODIR)
@@ -111,8 +106,5 @@ fclean: clean
 
 re: fclean all
 
-run:
-	@$(MAKE) all
+run: all
 	@./$(NAME)
-
-.PHONY: all libft clean fclean re run dependencies
