update

diff --git a/maincourse/fractol/-/Makefile b/maincourse/fractol/-/Makefile
--- a/maincourse/fractol/-/Makefile
+++ b/maincourse/fractol/-/Makefile
@@ -17,7 +17,7 @@ HEADERS = -I $(INCDIR) -I $(MLXDIR)/include
 DEPS = $(wildcard $(INCDIR)/*.h)
 
 # Source and Object Files
-SRCS = $(wildcard $(SDIR)/*.c) $(wildcard $(SDIR)/*/*.c)
+SRCS = $(shell find $(SDIR) -name '*.c')
 OBJS = $(SRCS:$(SDIR)/%.c=$(ODIR)/%.o)
 DEPFILES = $(OBJS:.o=.d) # Add this line to create dependency file paths
 
@@ -28,53 +28,53 @@ MLX_REPO = https://github.com/codam-coding-college/MLX42.git
 LIBS += -lglfw -L"/Users/$(USER)/.brew/opt/glfw/lib/" $(LIBMLX)
 HEADERS += -I $(INCDIR) -I $(MLXDIR)/include
 
-all: $(LIBMLX) $(NAME)
+all: dependdown $(LIBMLX) $(NAME)
 
 # Dependency handling rules
 -include $(DEPFILES) # Include the dependency files in the Makefile
 
 # Dependency installation (brew, cmake, glfw)
-# dependdown:
-# 	@if [ -x "$$HOME/homebrew/bin/brew" ] || [ -x "$$HOME/.brew/bin/brew" ]; then \
-# 		echo "brew is already installed"; \
-# 	else \
-# 		echo "Brew not found"; \
-# 		read -p "Do you want to install brew? y/n: "  brewchoice; \
-# 		if [ "$$brewchoice" = "y" ]; then \
-# 			rm -rf $$HOME/.brew && git clone --depth=1 https://github.com/Homebrew/brew $$HOME/.brew && \
-# 			echo 'export PATH=$$HOME/.brew/bin:$$PATH' >> $$HOME/.zshrc && source $$HOME/.zshrc && brew update; \
-# 			echo "Brew successfully installed"; \
-# 		else \
-# 			echo "Exit"; \
-# 			exit 2; \
-# 		fi \
-# 	fi
-# 	@if [ -d "$$HOME/homebrew/opt/cmake/bin" ] || [ -d "$$HOME/.brew/opt/cmake/bin" ]; then \
-# 		echo "cmake is already installed"; \
-# 	else \
-# 		echo "cmake not found"; \
-# 		read -p "Do you want to install cmake? y/n: " cmakechoice; \
-# 		if [ "$$cmakechoice" = "y" ]; then \
-# 			brew install cmake; \
-# 			echo "cmake successfully installed"; \
-# 		else \
-# 			echo "Exit"; \
-# 			exit 2; \
-# 		fi \
-# 	fi
-# 	@if [ -d "$$HOME/homebrew/opt/glfw/lib" ] || [ -d "$$HOME/.brew/opt/glfw/lib" ]; then \
-# 		echo "glfw is already installed"; \
-# 	else \
-# 		echo "glfw not found"; \
-# 		read -p "Do you want to install glfw? y/n: " glfwchoice; \
-# 		if [ "$$glfwchoice" = "y" ]; then \
-# 			brew install glfw; \
-# 			echo "glfw successfully installed"; \
-# 		else \
-# 			echo "Exit"; \
-# 			exit 2; \
-# 		fi \
-# 	fi
+dependdown:
+	@if [ -x "$$HOME/homebrew/bin/brew" ] || [ -x "$$HOME/.brew/bin/brew" ]; then \
+		echo "brew is already installed"; \
+	else \
+		echo "Brew not found"; \
+		read -p "Do you want to install brew? y/n: "  brewchoice; \
+		if [ "$$brewchoice" = "y" ]; then \
+			rm -rf $$HOME/.brew && git clone --depth=1 https://github.com/Homebrew/brew $$HOME/.brew && \
+			echo 'export PATH=$$HOME/.brew/bin:$$PATH' >> $$HOME/.zshrc && source $$HOME/.zshrc && brew update; \
+			echo "Brew successfully installed"; \
+		else \
+			echo "Exit"; \
+			exit 2; \
+		fi \
+	fi
+	@if [ -d "$$HOME/homebrew/opt/cmake/bin" ] || [ -d "$$HOME/.brew/opt/cmake/bin" ]; then \
+		echo "cmake is already installed"; \
+	else \
+		echo "cmake not found"; \
+		read -p "Do you want to install cmake? y/n: " cmakechoice; \
+		if [ "$$cmakechoice" = "y" ]; then \
+			brew install cmake; \
+			echo "cmake successfully installed"; \
+		else \
+			echo "Exit"; \
+			exit 2; \
+		fi \
+	fi
+	@if [ -d "$$HOME/homebrew/opt/glfw/lib" ] || [ -d "$$HOME/.brew/opt/glfw/lib" ]; then \
+		echo "glfw is already installed"; \
+	else \
+		echo "glfw not found"; \
+		read -p "Do you want to install glfw? y/n: " glfwchoice; \
+		if [ "$$glfwchoice" = "y" ]; then \
+			brew install glfw; \
+			echo "glfw successfully installed"; \
+		else \
+			echo "Exit"; \
+			exit 2; \
+		fi \
+	fi
 
 $(LIBMLX): $(MLXDIR)
 	@cmake $(MLXDIR) -B $(MLXDIR)/build && make -C $(MLXDIR)/build -j4
@@ -106,5 +106,3 @@ fclean: clean
 
 re: fclean all
 
-run: all
-	@./$(NAME)
